// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'},
    {
      type: 'link',
      label: 'Teaching',
      href: 'https://ncorwiki.buffalo.edu/index.php/Education',
    },
    {
      type: 'link',
      label: 'Iso Standard',
      href: 'https://ncorwiki.buffalo.edu/index.php/ISO_Standard',
    },
    {
      type: 'link',
      label: 'YouTube',
      href: 'https://www.youtube.com/channel/UCDYw4LTZfK27Q0lJ8pxQC8Q',
    },
    {
      type: 'link',
      label: 'Google Scholar',
      href: 'https://scholar.google.com/citations?user=icGNWj4AAAAJ&hl=en&pagesize=100',
    },
    {
      type: 'link',
      label: 'Contact',
      href: 'https://www.buffalo.edu/cas/philosophy/faculty/faculty_directory/smith-b.html',
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
